#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runApplication reconstructParMesh -constant

#------------------------------------------------------------------------------
