FROM opencfd/openfoam-run:2206

RUN apt-get update && \
    apt-get install -y openssh-server vim

EXPOSE 22

# SSH
RUN apt-get -y install openssh-server
RUN mkdir -p /var/run/sshd

# authorize SSH connection with root account
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo 'export NOTVISIBLE="in users profile"' >> ~/.bashrc && \
    echo "export VISIBLE=now" >> /etc/profile

RUN sudo service ssh restart

# change password root
RUN echo "root:docker"|chpasswd

# @see https://docs.docker.com/engine/examples/running_ssh_service/
CMD ["/usr/sbin/sshd", "-D"]
