#!/bin/sh
cd "${0%/*}" || exit 1    # run from this directory

# Source tutorial clean functions
. /opt/openfoam9/bin/tools/CleanFunctions

cleanCase

#------------------------------------------------------------------------------
