#!/bin/sh

cd ${0%/*} || exit 1

. /opt/openfoam9/bin/tools/RunFunctions

# Create the initial block mesh and decompose
runApplication blockMesh
# runApplication decomposePar -copyZero

# Split the mesh into regions
runParallel splitMeshRegions -cellZones -defaultRegionName solid -overwrite
