#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh

runParallel $(getApplication)

runApplication reconstructParMesh -allRegions -constant
runApplication reconstructPar -allRegions

paraFoam -touchAll
